name: deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "building!"
      name: Building

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # environment: production
    steps:
    - run: echo "deploying!"
      name: deploying
