name: deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_WIDE: ${{ 'hello' != 'hi' && 'true' || '' }}
      JOB_WIDE_EMPTY: ${{ 'hello' == 'hi' && 'true' || '' }}
    steps:
    - run: echo hi
      if: env.JOB_WIDE_EMPTY
    - run: echo hi
      if: env.JOB_WIDE
    - run: |
        echo "building!" ${{ env.BUILD }} 
        echo ${{ env.BUILD == 'true' }}
        echo ${{ env.BUILD == 'false' }}
      name: Building
      env:
        BUILD: ${{ 'hello' == 'hi' }} 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # environment: production
    permissions:
      contents: write
    steps:
    - run: echo "deploying!"
      name: deploying
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}.wiki
    - name: configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Make change
      run: |
        echo "Hello world!" > file.txt
        git add file.txt
        git commit -m "Add file.txt"
    - name: Push
      run: |
        git push
