name: test

on: push

jobs:
  build:
    if: 'false'
    strategy:
      matrix:
        name: [build1, build2]
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    outputs: ${{ fromJson(format('{ "name": "{0}-{1}" }', matrix.name, steps.build.outputs.version )) }}
    steps:
    - run: |
        echo ${{ format('hello', 'world') }}
        echo "building!"
        echo "version=1" >> "$GITHUB_OUTPUT"
      id: build
      name: Building

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ needs.build.outputs.name }}
        echo ${{ needs.build1.outputs.name }}
        echo ${{ needs.build2.outputs.name }}
        echo ${{ needs.build.build1.outputs.name }}
        echo ${{ needs.build.build2.outputs.name }}
      name: deploying
